spring.application.name=personalFinanceTracker

#port-number
server.port=8080

#SQL
spring.datasource.url=jdbc:mysql://localhost:3306/personal_finance_tracker
spring.datasource.username=root
spring.datasource.password=@Gg28602
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=false
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

